### ISSUE TITLE
Add samtool quick check 

### ISSUE THREAD

**Issue by moonso** [Clinical-Genomics/crunchy#5]
This should be done in the bam to cram process

**Comment by moonso** [comment]
And cram -> bam ?

**Comment by moonso** [comment]
@henrikstranneheim this check seems useless for our needs. I have tried to manipulate a bam file to make the check fail and it always returns success. If we want to find small conversion errors this is not the way to go unfortunately.

**Comment by henrikstranneheim** [comment]
It only looks at the EOF flag in the file and not at the specific format (hence the quick part). It is very simple but it means that the upstream process at least finished.

**Comment by henrikstranneheim** [comment]
Otherwise one should use picardtools validatesam or such, but they are slower
